<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container8jO2Ial\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container8jO2Ial/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container8jO2Ial.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container8jO2Ial\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container8jO2Ial\App_KernelDevDebugContainer([
    'container.build_hash' => '8jO2Ial',
    'container.build_id' => '9bee44e3',
    'container.build_time' => 1733509150,
], __DIR__.\DIRECTORY_SEPARATOR.'Container8jO2Ial');
